# Generated by Django 4.0.4 on 2022-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrôle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='verification',
            field=models.CharField(default='exit', max_length=10000),
            preserve_default=False,
        ),
    ]
