# Generated by Django 4.0.4 on 2022-05-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrôle', '0002_controle_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controle',
            name='description',
        ),
    ]
