# Generated by Django 4.0.4 on 2022-05-23 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contrôle', '0003_remove_controle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='champVerification',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000),
            preserve_default=False,
        ),
    ]
