# Generated by Django 4.0.4 on 2022-05-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rapport',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='data_creation',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='log',
            name='nom_utilisateur',
        ),
        migrations.RemoveField(
            model_name='log',
            name='type_operation',
        ),
        migrations.AddField(
            model_name='log',
            name='ip',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='procedure',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='rapport',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='routine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
