# Generated by Django 4.0.4 on 2022-04-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='nom_equipement',
            new_name='nom_equipemen',
        ),
    ]
